<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BDX.io - PDF Tour de cou</title>
</head>
<body>
<h1>BDX.io - Génération des tours de Cou</h1>
<p>
	Pour lancer la génération des badges, et la récuperer il faut : 
</p>
<ol class="nav">
	<li>Dans le répertoire : <em>application/datas</em> copier le fichier csv des inscrits, par défaut l'application cherche le fichier <em><strong>inscrits.csv</strong></em></li>
	<li>
		Dans le répertoire, <em>application/datas/images/</em> Mettre les nouvelles images, à la racine. Les images doivent avoir les noms suivants: 
	</li>
    <li><a href="/tour">Lancer la génération</a></li>
</ol>
</body>
</html>