<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
<a href="/index/delete">Supprimer les anciens fichiers</a>
<ul>

    <?php
    foreach($this->files as $file){
        echo "<li>";
        echo '<a target="_blank" href="/pdf/'.substr($file, strrpos($file, '/')+1).'">';
        echo $file;
        echo "</a> -- ";
        echo '<a target="_blank" href="/index/update/file/'.substr($file, strrpos($file, '/')+1).'">METTRE A JOUR DANS LA SPREADSHEET (KO)</a>';
        echo "</li>";
    }
    ?>
</ul>
</body>
</html>